#!/bin/bash
### BEGIN INIT INFO
# Provides:          mcserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $portmap
# Should-Stop:       $portmap
# X-Start-Before:    nis
# X-Stop-After:      nis
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: mcserver
# Description:       used to automatically start/stop mcserver
### END INIT INFO

case "$1" in
    start)
        su - shamus03 -c "mcserver start survival"
        ;;
    stop)
        su - shamus03 -c "mcserver stop survival"
        echo "Sleeping to allow servers to shut down completely."
        sleep 10
        ;;
    restart)
        su - shamus03 -c "mcserver restart survival"
        ;;
    *)
        echo "Usage $0 {start|stop|restart|}"
        exit 1
        ;;
esac

exit 0